### ISSUE TITLE
Register the package

### ISSUE THREAD

**Issue by babaq** [circstat/CircStats.jl#5]
Hi @philippberens,

I think the package is ready to be registered in the default Julia package registry, so that user can just use Julia package manager, and type `add CircStats` to install the package.

Since i don't have access to the repository, the easiest way for you to register is go to [Juliahub register page](https://juliahub.com/ui/Registrator), and it should be easy to complete the whole process manually.

Thanks,
Alex

**Comment by philippberens** [comment]
Ok, I did that.
