### ISSUE TITLE
Use `cis(a)` rather than `exp(im*a)`

### ISSUE THREAD

**Issue by oscardssmith** [circstat/CircStats.jl#6]
It's 24% faster and at least as accurate.

**Comment by oscardssmith** [comment]
Similarly, `mod2pi(a)` should be used instead of `mod(a, 2pi)`.

**Comment by philippberens** [comment]
tagging @babaq

**Comment by babaq** [comment]
issue solved in #7 
@philippberens after merging, and package registration completion, you can use the same JuliaHub register page to publish this v1.0.1 version.

**Comment by babaq** [comment]
@philippberens The v1.0.0 version have been accepted in general Julia package registry!

Now, you can publish the current version v1.0.1
